version: '3.0'
services:
  dev:
    image: 'dragonglassobsidian/obsidian-demo-prod'
    container_name: obsidian-demo-prod-container
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/app
    command: deno run --allow-net --allow-read --allow-env --unstable new-server.tsx
    depends_on:
      - redis-db
  redis-db:
    image: dragonglassobsidian/obsidian-redis
    container_name: obsidian-redis-database
    ports:
      - '6379:6379'
    hostname: redis
    command: ['redis-server', '--bind', '0.0.0.0', '--port', '6379']
    volumes:
      - dev-redis-volume:/var/lib/redis/data
volumes:
  dev-redis-volume:
